# Generated by Django 3.2.6 on 2021-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
