# Generated by Django 3.2.6 on 2021-08-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_board_board_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('공지', '공지'), ('잡담', '잡담'), ('후기', '후기')], default='잡담', max_length=20),
        ),
    ]
