# Generated by Django 3.2.6 on 2021-08-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_free'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Free',
        ),
    ]
